### ISSUE TITLE
Duda: Como bloquear comandos y usar el tabcomplete

### ISSUE THREAD

**Issue by Pachecon22** [Ajneb97/EasyCommandBlocker#7]
Buenas, me gustaría saber como se puede hacer que el plugin bloquee **TODOS** los comandos del servidor (que ponga bloquee la acción) **EXCEPTO** los que hay definidos en la configuración del plugin.
Actualmente no se como hacer esto, recuerdo que hace 1 año esto era posible, ya que lo hacia en mi servidor de pruebas, pero actualmente no se como se haría esto.
Gracias de antemano.

**Comment by Ajneb97** [comment]
La opcion use_commands_as_whitelist la pones en true, y en la opción commands, defines los comandos que quieres que puedan usar los usuarios

**Comment by Pachecon22** [comment]
Y se podria hacer que los comandos de la opcion commands estuvieran en cada rango? o simplemente con que tengan acceso cada rango a los comandos ya les aparecería.
Me explico, si por ejemplo el grupo "default" tiene permiso para el /home, le saldria el comando y el grupo "vip" tendria acceso al /nick, ¿al usuario en el grupo default tambien le aparecería el comando /nick?

**Comment by Ajneb97** [comment]
Pero para eso el plugin que implementa ese comando debe tener un sistema de permisos para prevenir que ciertos usuarios lo usen.

**Comment by Pachecon22** [comment]
Ok, mantengo el hilo abierto, probaré más tarde
